# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Set plugins
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji

# Site settings
url: 'https://wenqinglim.github.io'
baseurl: ''
title: "Wen Qing Lim"
description: '🤓'
permalink: pretty
# logo: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=52"

# Pagination
paginate: 5
paginate_path: blog/page:num
twitter:
  username: omgitsqing # jekyll-seo-tag > Owners twitter username
author: WenQingLim # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Wen Qing Lim # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/omgitsqing
    - https://www.linkedin.com/in/wen-qing-l-67330771/
    - https://github.com/wenqinglim
    - https://codingintune.substack.com/
    - https://medium.com/@limwenqing


# Header nav
navigation_header:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Resume
    url: /resume/

# Footer nav
navigation_footer:
  - title: Back to top
    url: "#top"


social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/omgitsqing
  LinkedIn: https://www.linkedin.com/in/wen-qing-l-67330771/
  GitHub: https://github.com/wenqinglim
  link: https://codingintune.substack.com/

# Collections
# collections:
#   posts:
#     title: Posts
#     output: true
#     description: "My thoughts and ideas"
#     feature_text: |
#       Welcome to my blog
#     feature_image: "https://picsum.photos/2560/600?image=866"

# Collection settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
